name: torchmd-net
channels:
  # - raimis
  # - mmh
  - conda-forge
dependencies:
  - ase
  - h5py
  - matplotlib
  - nnpops
  - pip
  - python
  # - pytorch==1.10.0
  - pytorch_cluster
  - pytorch_geometric
  - pytorch-lightning==1.3.8
  - torchani
  - torchmetrics <0.8
  - tqdm
  # Dev tools
  - flake8
  - pytest