name: torchmd-net
channels:
  - conda-forge
dependencies:
  - h5py
  - matplotlib-base
  - nnpops==0.6
  - pip
  - pytorch==2.0.*
  - pytorch_geometric==2.4.0
  - lightning==2.1.2
  - pydantic<2
  - torchmetrics==1.2.1
  - tqdm
  # Dev tools
  - flake8
  - pytest
  - psutil
  - gxx
