name: torchmd-net
channels:
  - conda-forge
dependencies:
  - h5py
  - matplotlib-base
  - nnpops
  - pip
  - pytorch==2.*
  - pytorch_geometric==2.4.*
  - lightning==2.1.*
  - pydantic
  - torchmetrics
  - tqdm
  # Dev tools
  - flake8
  - pytest
  - psutil
  - gxx<12
