[project]
name = "torchmd-net"
description = "TorchMD-Net package"
authors = [{ name = "CompScienceLab", email = "gianni.defabritiis@upf.edu" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dynamic = ["version"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: POSIX :: Linux",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/torchmd/torchmd-net"
"Bug Tracker" = "https://github.com/torchmd/torchmd-net/issues"

[project.scripts]
torchmd-train = "torchmdnet.scripts.train:main"

[tool.setuptools.packages.find]
where = [""]
include = ["torchmdnet*"]
namespaces = false

[tool.setuptools.package-data]
torchmdnet = ["extensions/torchmdnet_extensions.so"]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "torchmdnet/_version.py"
versionfile_build = "torchmdnet/_version.py"
tag_prefix = ""
parentdir_prefix = "torchmdnet-"

[build-system]
requires = ["setuptools", "toml", "versioneer[toml]==0.28", "torch<2.2"]
build-backend = "setuptools.build_meta"
