activation: silu
batch_size: 128
cutoff_lower: 0.0
cutoff_upper: 5.0
distributed_backend: ddp
early_stopping_patience: 100
embedding_dimension: 256
inference_batch_size: 128
label: energy_U0
lr: 4e-4
lr_factor: 0.8
lr_min: 1e-7
lr_patience: 15
lr_warmup_steps: 0
neighbor_embedding: true
ngpus: -1
num_epochs: 3000
num_filters: 256
num_interactions: 6
num_nodes: 1
num_rbf: 64
num_workers: 4
rbf_type: expnorm
save_interval: 10
seed: 1
test_interval: 10
test_ratio: 0.10922
trainable_rbf: true
val_ratio: 0.05
weight_decay: 0.0
