name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 0:00

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "macos-13", "windows-2022"]
        python-version: ["3.10"] #, "3.9", "3.11", "3.12"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults

      - name: Remove conflicting Visual Studio compiler (Windows only)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          del "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe"
          del "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe"

      - name: Install OS-specific conda dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            conda install --file conda_deps_linux.txt
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            conda install --file conda_deps_osx.txt
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            conda install --file conda_deps_win.txt
          fi

      - name: Install testing packages
        run: conda install -y -c conda-forge flake8 pytest psutil

      - name: List the conda environment
        run: conda list

      - name: Build and install the package
        run: pip -vv install .
        env:
          CPU_ONLY: 1

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: pytest -v -s

      - name: Test torchmd-train utility
        run: torchmd-train --help
